### PR TITLE
Simplify tunnel sync code

### PR DESCRIPTION
**Pull request by aledbf**
- [ ] I have raised an issue to propose this change.

## Description

Change if-else statements to make code easier to read and also filter services by type before sending it to the work queue 

## How Has This Been Tested?

This is being tested while I am evaluating inlets-pro in a four NUC node k8s cluster using k3os and DigitalOcean as provider

## How are existing users impacted? What migration steps/scripts do we need?

There is no impact or migration needed.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [X] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [X] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @aledbf, thank you for taking time to contribute to inlets.

I appreciate you're a busy guy, but please can you fill out the whole PR template including how you tested the change?

> How Has This Been Tested?

Thanks,

Alex

**Comment by aledbf** [comment]
> I appreciate you're a busy guy, but please can you fill out the whole PR template including how you tested the change?

Sorry about that.

**Comment by alexellis** [comment]
Can you talk me through the change? I'm not following it.

**Comment by aledbf** [comment]
> Can you talk me through the change? I'm not following it.

I was trying to do this in two PRs, but I just pushed all the changes. I found the resync used any service in the resource handlers and not only type=LoadBalancer (this was done internally) and the log of the pod looked confusing, showing syncs from services of type=ClusterIP (and I have more than 50)

**Comment by alexellis** [comment]
That makes a lot of sense when you explain it.

Would you mind putting a separate PR in for the `checkServiceType` part? I'll get that merged and released this weekend if you can get something up for it.

**Comment by aledbf** [comment]
> Would you mind putting a separate PR in for the checkServiceType part?

Done. Once this PR is merged I will open a new one with the checkServiceType

**Comment by alexellis** [comment]
Just realised that @zechenbit had a PR very similar to this that got merged first. Sorry about that.

Is there anything remaining here that you'd like to see us include in the code?

**Comment by aledbf** [comment]
> Is there anything remaining here that you'd like to see us include in the code?

Not sure. I'll check the current code and open a new PR if I see something could be improved

**Pull request closed without merging**
